### ISSUE TITLE
[Bug] ALmost all of the STL and STEP files are invalid.

### ISSUE THREAD

**Issue by NanashiTheNameless** [Shock-Link/3DPrints#5]
a dump of one such file obtained with cat is as follows 
```
version https://git-lfs.github.com/spec/v1
oid sha256:00e861d21d0ae0ea974014be77cd28b289b41387b72379cc6ab56aa01c85cb8f
size 393498
```
that is the entire file
the file "LolaSpacer - NullSlim.step" seems to be the only correct step file

**Comment by hhvrc** [comment]
This is git-lfs, github will not give you the files if you just download them all as a zip file, you need to download them individually or by using git lfs on a cloned repo

**Comment by NanashiTheNameless** [comment]
was about to say i just figured* that out
maybe adding info in the readme would be helpful?

**Comment by LucHeart** [comment]
This is expected behaviour and common knowledge imo. Can add to readme tho
